# Deploy app to /api/
#server:
#    contextPath: '/api'
#grails:
#    app:
#        context: '/api'
---
#Default for plugins/applications
---
grails:
    profile: rest-api-plugin
    codegen:
        defaultPackage: uk.ac.ox.softeng.maurodatamapper.core
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    exceptionresolver:
        params:
            exclude:
                - password
                - tempPassword
    cors:
        enabled: true
        # The following are the defaults
        #allowedOrigins: ['*']
        allowedMethods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'HEAD']
        allowedHeaders: ['origin', 'content-type', 'accept', 'authorization']
        #exposedHeaders: null
        #maxAge: 1800
        #allowCredentials: true
    views:
        markup:
            autoEscape: true
            prettyPrint: false
            autoIndent: false
            autoNewLine: false
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
---
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQL95Dialect
    formatSql: true
    url: 'jdbc:postgresql://${database.host}:${database.port}/${database.name}'
    dbCreate: none
---
environments:
    test:
        flyway.enabled: false
        dataSource:
            driverClassName: org.h2.Driver
            dialect: org.hibernate.dialect.H2Dialect
            username: sa
            password: ''
            dbCreate: update
            url: 'jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL'
    development:
#        flyway.enabled: false
        dataSource:
#            dbCreate: create
            username: metadatacatalogue
            password: MetadataCatalogue1234
